name: Deploy static content to Pages

on:
  # Runs on pushes targeting the new-branch branch
  push:
    branches: 
      - new-branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build
        run: |
          # Replace this with your build command (e.g., npm run build)
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Specify the directory where your built static files are located
